FROM openjdk:8-jre-alpine
MAINTAINER Ciberdix
ENTRYPOINT ["/usr/bin/java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/var/lib/jenkins/.m2/repository/com/shsolutions/project/negocio/0.0.1-SNAPSHOT/negocio-0.0.1-SNAPSHOT.jar"]