FROM openjdk:8-jre-alpine
MAINTAINER Ciberdix
ENTRYPOINT ["/usr/bin/java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/var/lib/jenkins/workspace/sh/negocio/target/negocio-0.0.1-SNAPSHOT.jar"]